version: '3'

services:
  db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=dslqueueDatabase
    networks:
      - mynetwork
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1234
    depends_on:
      - db
    networks:
      - mynetwork

  api:
    build: ./DSL-queue-back-end
    environment:
       PORT: 8886
       VUE_APP_GOOGLE_CLIENT_ID: 104159606172-s0po212319hq48u8k9cn0cr6ga59pg7n.apps.googleusercontent.com
       DATABASE_URL: mysql://root:1234@db:3306/dslqueueDatabase
       GOOGLE_CLIENT_ID: 104159606172-s0po212319hq48u8k9cn0cr6ga59pg7n.apps.googleusercontent.com
       GOOGLE_CLIENT_SECRET: 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
       ACCESS_SECRET: ACCESS_SECRET_ANG_JAAA
       REFRESH_SECRET: REFRESH_SECRET_ANG_JAAA
    ports:
      - '8886:8886'
    networks:
      - mynetwork
    depends_on:
      - db
    restart: unless-stopped

  vue-app:
    build: ./dsl-queue-vue-2
    container_name: vue-app
    volumes:
      - ./dsl-queue-vue-2/dist:/usr/share/nginx/html
    expose:
      - "80"
    networks:
      - mynetwork
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - ./dsl-queue-vue-2/dist:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      # - vue-app
      - api
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  vue-build:
    