services:
  db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=dslqueueDatabase
    networks:
      - mynetwork
    restart: unless-stopped
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1234
    depends_on:
      - db
    networks:
      - mynetwork
  api:
    build: .
    environment:
       PORT: 8886
       VUE_APP_GOOGLE_CLIENT_ID: 104159606172-s0po212319hq48u8k9cn0cr6ga59pg7n.apps.googleusercontent.com
       DATABASE_URL: mysql://root:1234@db:3306/dslqueueDatabase
       GOOGLE_CLIENT_ID: 104159606172-s0po212319hq48u8k9cn0cr6ga59pg7n.apps.googleusercontent.com
       GOOGLE_CLIENT_SECRET: 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
       ACCESS_SECRET: ACCESS_SECRET_ANG_JAAA
       REFRESH_SECRET: REFRESH_SECRET_ANG_JAAA
    ports:
      - '8886:8886'
    networks:
      - mynetwork
    depends_on:
      - db
    restart: unless-stopped
networks:
  mynetwork:
    driver: bridge
